spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/salestorm}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:salestorm_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:salestorm_password}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.kafka.enabled=${APP_KAFKA_ENABLED:true}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID:salestorm-order-group}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

app.redis.enabled=${APP_REDIS_ENABLED:true}
spring.data.redis.host=${SPRING_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}

# Observability & Health
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true

# Graceful Shutdown
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
